Traceback (most recent call last):
  File "main.py", line 31, in <module>
    CNPM().run()
  File "C:\Users\binng\anaconda3\envs\kivyconda\lib\site-packages\kivy\app.py", line 950, in run
    runTouchApp()
  File "C:\Users\binng\anaconda3\envs\kivyconda\lib\site-packages\kivy\base.py", line 582, in runTouchApp
    EventLoop.mainloop()
  File "C:\Users\binng\anaconda3\envs\kivyconda\lib\site-packages\kivy\base.py", line 347, in mainloop
    self.idle()
  File "C:\Users\binng\anaconda3\envs\kivyconda\lib\site-packages\kivy\base.py", line 387, in idle
    Clock.tick()
  File "C:\Users\binng\anaconda3\envs\kivyconda\lib\site-packages\kivy\clock.py", line 733, in tick
    self.post_idle(ts, self.idle())
  File "C:\Users\binng\anaconda3\envs\kivyconda\lib\site-packages\kivy\clock.py", line 776, in post_idle
    self._process_events()
  File "kivy\_clock.pyx", line 616, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 645, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "C:\Users\binng\anaconda3\envs\kivyconda\lib\site-packages\kivymd\uix\datatables.py", line 722, in set_default_first_row
    self.ids.row_controller.select_next(self)
  File "C:\Users\binng\anaconda3\envs\kivyconda\lib\site-packages\kivymd\uix\datatables.py", line 355, in select_next
    self.select_row(nodes)
  File "C:\Users\binng\anaconda3\envs\kivyconda\lib\site-packages\kivymd\uix\datatables.py", line 368, in select_row
    col = self.table_data.recycle_data[self.selected_row]["range"]
IndexError: list index out of range
